//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_TTEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter_Change_Log
    {
        public string Logged_User { get; set; }
        public Nullable<short> User_Group_Number { get; set; }
        public string Parameter_Changed { get; set; }
        public string Actual_Value { get; set; }
        public string Old_Value { get; set; }
        public string Time_Of_Change { get; set; }
        public string Date_Of_Change { get; set; }
        public long ID { get; set; }
    }
}
